export const Prize = {
    redBenz: 1,
    greenBenz: 2,
    yellowBenz: 3,
    redBmw: 4,
    greenBmw: 5,
    yellowBmw: 6,
    redAudi: 7,
    greenAudi: 8,
    yellowAudi: 9,
    redVm: 10,
    greenVm: 11,
    yellowVm: 12,
    sanyuanAudi: 21,
    sanyuanVm: 22,
    sanyuanBenz: 31,
    sanyuanBmw: 32,
    siXiRed: 41,
    siXiGreen: 42,
    siXiYellow: 43,
    daManguan: 100,
    zhuangChi: -100,
    error: 0
}
